# Generated by Django 5.0.2 on 2024-02-06 23:38
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_task_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, serialize=False)),
                ('id', models.AutoField(primary_key=True, serialize=False))
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_task_api_app.person')),
            ],
        ),
    ]
